using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AutoPower.SourceGenerator;

[Generator]
public sealed class LocalizerGenerator : IIncrementalGenerator
{
    private const string MarkerAttributeName = "AutoPower.SourceGenerator.LocalizerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit the marker attribute so consuming projects can reference it
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("LocalizerAttribute.g.cs", SourceText.From(@"
namespace AutoPower.SourceGenerator
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class LocalizerAttribute : global::System.Attribute { }
}
", Encoding.UTF8));
        });

        // Step 1: Find [Localizer] attribute on partial classes
        var markerClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MarkerAttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetMarkerClassInfo(ctx))
            .Where(static m => m is not null);

        // Step 2: Collect all AdditionalFiles that match Strings_*.json
        var jsonFiles = context.AdditionalTextsProvider
            .Where(static file => Path.GetFileName(file.Path).StartsWith("Strings_", StringComparison.Ordinal)
                               && file.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase));

        // Step 3: Combine marker class with all JSON file contents
        var combined = markerClasses
            .Combine(jsonFiles.Collect())
            .Combine(context.CompilationProvider);

        // Step 4: Generate source
        context.RegisterSourceOutput(combined, static (spc, data) =>
        {
            var (markerAndFiles, compilation) = data;
            var (markerClass, jsonFiles) = markerAndFiles;
            if (markerClass is null)
                return;

            GenerateSource(spc, markerClass, jsonFiles, compilation);
        });
    }

    private static MarkerClassInfo? GetMarkerClassInfo(GeneratorAttributeSyntaxContext ctx)
    {
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        return new MarkerClassInfo(
            classSymbol.ContainingNamespace.ToDisplayString(),
            classSymbol.Name,
            classSymbol.DeclaredAccessibility == Accessibility.Public
        );
    }

    private static void GenerateSource(
        SourceProductionContext context,
        MarkerClassInfo classInfo,
        ImmutableArray<AdditionalText> jsonFiles,
        Compilation compilation)
    {
        // Parse all JSON files into culture -> (key -> value) maps
        var cultures = new SortedDictionary<string, Dictionary<string, string>>();
        var defaultCulture = "en";

        foreach (var file in jsonFiles)
        {
            var fileName = Path.GetFileNameWithoutExtension(file.Path); // e.g. "Strings_en" or "Strings_zh"
            var sourceText = file.GetText(context.CancellationToken);
            if (sourceText is null)
                continue;

            // Extract culture from filename: Strings_<culture>.json
            var underscoreIndex = fileName.IndexOf('_');
            if (underscoreIndex < 0 || underscoreIndex >= fileName.Length - 1)
                continue;

            var culture = fileName.Substring(underscoreIndex + 1);

            var entries = ParseFlatJson(sourceText.ToString());
            if (entries.Count > 0)
            {
                cultures[culture] = entries;
            }
        }

        if (cultures.Count == 0)
            return;

        // Use "en" as default if present, otherwise use the first culture
        if (!cultures.ContainsKey(defaultCulture) && cultures.Count > 0)
            defaultCulture = cultures.Keys.First();

        // Collect all unique keys across all cultures (sorted for deterministic output)
        var allKeys = new SortedSet<string>();
        foreach (var entries in cultures.Values)
        {
            foreach (var key in entries.Keys)
                allKeys.Add(key);
        }

        if (allKeys.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(classInfo.Namespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("using System;");
        sb.AppendLine();
        sb.Append("using System.Collections.Generic;");
        sb.AppendLine();
        sb.Append("using System.Globalization;");
        sb.AppendLine();
        sb.AppendLine();

        // Accessibility
        sb.Append(classInfo.IsPublic ? "public" : "internal");
        sb.Append(" static partial class ").AppendLine(classInfo.ClassName);
        sb.AppendLine("{");

        // Generate resource dictionaries
        sb.AppendLine("    private static readonly Dictionary<string, string> _en = new Dictionary<string, string>");
        sb.AppendLine("    {");
        if (cultures.TryGetValue("en", out var enEntries))
        {
            foreach (var key in allKeys)
            {
                if (enEntries.TryGetValue(key, out var value))
                {
                    sb.Append("        [\"").Append(EscapeString(key)).Append("\"] = \"")
                      .Append(EscapeString(value)).AppendLine("\",");
                }
            }
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        foreach (var culture in cultures.Keys.Where(c => c != "en"))
        {
            sb.Append("    private static readonly Dictionary<string, string> _")
              .Append(SanitizeIdentifier(culture))
              .AppendLine(" = new Dictionary<string, string>");
            sb.AppendLine("    {");
            if (cultures.TryGetValue(culture, out var entries))
            {
                foreach (var key in allKeys)
                {
                    if (entries.TryGetValue(key, out var value))
                    {
                        sb.Append("        [\"").Append(EscapeString(key)).Append("\"] = \"")
                          .Append(EscapeString(value)).AppendLine("\",");
                    }
                }
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        // Generate culture lookup
        sb.AppendLine("    private static string Get(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        var culture = CultureInfo.CurrentUICulture;");
        sb.AppendLine("        var cultureName = culture.Name;");
        sb.AppendLine("        var twoLetter = culture.TwoLetterISOLanguageName;");
        sb.AppendLine();

        // Build lookup chain: specific -> two-letter -> en
        sb.AppendLine("        Dictionary<string, string> dict;");
        sb.AppendLine("        if (cultureName.Length >= 5)");
        sb.AppendLine("        {");
        sb.Append("            switch (cultureName.ToLowerInvariant())");
        sb.AppendLine("            {");
        foreach (var culture in cultures.Keys.Where(c => c != "en"))
        {
            sb.Append("                case \"").Append(culture.ToLowerInvariant()).Append("\": dict = _")
              .Append(SanitizeIdentifier(culture)).AppendLine("; break;");
        }
        sb.AppendLine("                default: dict = _en; break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.Append("            switch (twoLetter.ToLowerInvariant())");
        sb.AppendLine("            {");
        // Deduplicate: group cultures by two-letter prefix, use first match
        var twoLetterGroups = cultures.Keys
            .Where(c => c != "en")
            .GroupBy(c => c.ToLowerInvariant().Substring(0, 2))
            .ToDictionary(g => g.Key, g => g.First());
        foreach (var kvp in twoLetterGroups)
        {
            sb.Append("                case \"").Append(kvp.Key)
              .Append("\": dict = _").Append(SanitizeIdentifier(kvp.Value)).AppendLine("; break;");
        }
        sb.AppendLine("                default: dict = _en; break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return dict.TryGetValue(key, out var value) ? value : _en.TryGetValue(key, out var fallback) ? fallback : key;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate properties for each key
        foreach (var key in allKeys)
        {
            var propertyName = SanitizePropertyName(key);
            var hasFormatPlaceholder = enEntries != null
                && enEntries.TryGetValue(key, out var enValue)
                && (enValue.Contains("{0}") || enValue.Contains("{1}") || enValue.Contains("{2}"));

            if (hasFormatPlaceholder)
            {
                // Generate format method
                var paramCount = CountFormatParameters(enEntries![key]);
                sb.Append("    public static string ").Append(propertyName).Append("(");
                for (int i = 0; i < paramCount; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append("object arg").Append(i);
                }
                sb.AppendLine(")");
                sb.AppendLine("    {");
                sb.Append("        return string.Format(Get(\"").Append(EscapeString(key)).Append("\")");
                for (int i = 0; i < paramCount; i++)
                {
                    sb.Append(", arg").Append(i);
                }
                sb.AppendLine(");");
                sb.AppendLine("    }");
            }
            else
            {
                // Generate simple property
                sb.Append("    public static string ").Append(propertyName)
                  .Append(" => Get(\"").Append(EscapeString(key)).AppendLine("\");");
            }
        }

        sb.AppendLine("}");

        context.AddSource(classInfo.ClassName + ".g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Parse a flat JSON object into key-value pairs. Handles nested objects with dot notation.
    /// Does NOT use System.Text.Json (netstandard2.0 compatible).
    /// </summary>
    private static Dictionary<string, string> ParseFlatJson(string json)
    {
        var result = new Dictionary<string, string>();
        ParseJsonObject(json, 0, "", result);
        return result;
    }

    private static int ParseJsonObject(string json, int index, string prefix, Dictionary<string, string> result)
    {
        index = SkipWhitespace(json, index);
        if (index >= json.Length || json[index] != '{')
            return index;
        index++; // skip '{'

        while (index < json.Length)
        {
            index = SkipWhitespace(json, index);
            if (index >= json.Length) break;
            if (json[index] == '}') { index++; return index; }
            if (json[index] == ',') { index++; continue; }

            // Parse key
            var key = ParseJsonString(json, ref index);
            if (key == null) break;

            index = SkipWhitespace(json, index);
            if (index >= json.Length || json[index] != ':') break;
            index++; // skip ':'
            index = SkipWhitespace(json, index);

            if (index >= json.Length) break;

            var fullKey = string.IsNullOrEmpty(prefix) ? key : prefix + "." + key;

            if (json[index] == '{')
            {
                // Nested object
                index = ParseJsonObject(json, index, fullKey, result);
            }
            else if (json[index] == '"')
            {
                // String value
                var value = ParseJsonString(json, ref index);
                if (value != null)
                {
                    result[fullKey] = value;
                }
            }
            else
            {
                // Skip non-string values (numbers, booleans, null)
                index = SkipValue(json, index);
            }
        }

        return index;
    }

    private static string? ParseJsonString(string json, ref int index)
    {
        if (index >= json.Length || json[index] != '"')
            return null;

        index++; // skip opening quote
        var sb = new StringBuilder();

        while (index < json.Length)
        {
            if (json[index] == '\\')
            {
                index++;
                if (index >= json.Length) break;
                switch (json[index])
                {
                    case '"': sb.Append('"'); break;
                    case '\\': sb.Append('\\'); break;
                    case '/': sb.Append('/'); break;
                    case 'n': sb.Append('\n'); break;
                    case 'r': sb.Append('\r'); break;
                    case 't': sb.Append('\t'); break;
                    case 'b': sb.Append('\b'); break;
                    case 'f': sb.Append('\f'); break;
                    case 'u':
                        if (index + 4 < json.Length)
                        {
                            var hex = json.Substring(index + 1, 4);
                            if (int.TryParse(hex, System.Globalization.NumberStyles.HexNumber, null, out var code))
                            {
                                sb.Append((char)code);
                            }
                            index += 4;
                        }
                        break;
                    default: sb.Append(json[index]); break;
                }
                index++;
            }
            else if (json[index] == '"')
            {
                index++; // skip closing quote
                return sb.ToString();
            }
            else
            {
                sb.Append(json[index]);
                index++;
            }
        }

        return sb.ToString();
    }

    private static int SkipWhitespace(string json, int index)
    {
        while (index < json.Length && (json[index] == ' ' || json[index] == '\t' || json[index] == '\r' || json[index] == '\n'))
            index++;
        return index;
    }

    private static int SkipValue(string json, int index)
    {
        if (index >= json.Length) return index;

        // Skip number, boolean, null
        while (index < json.Length && json[index] != ',' && json[index] != '}' && json[index] != ']')
            index++;
        return index;
    }

    private static int CountFormatParameters(string format)
    {
        int max = -1;
        for (int i = 0; i < format.Length - 1; i++)
        {
            if (format[i] == '{' && format[i + 1] >= '0' && format[i + 1] <= '9')
            {
                var digit = format[i + 1] - '0';
                if (digit > max) max = digit;
            }
        }
        return max + 1;
    }

    private static string EscapeString(string s)
    {
        return s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static string SanitizePropertyName(string key)
    {
        // Convert dot-separated key to PascalCase
        var parts = key.Split('.');
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0) continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part.Substring(1));
        }
        return sb.ToString();
    }

    private sealed class MarkerClassInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public bool IsPublic { get; }

        public MarkerClassInfo(string ns, string name, bool isPublic)
        {
            Namespace = ns;
            ClassName = name;
            IsPublic = isPublic;
        }
    }
}
